                xoay(k);
                a[k]=1;
                if(check(x,y,k)){
                    sol.push_back(make_pair(x,y));
                    if(k==n-1)state=true;
                    TRY(k+1);
                    sol.pop_back();
                    xoay(k);
                    a[k]=0;
                }